### ISSUE TITLE
[Bug] Could not invoke RNTapResearch.initWithApiToken

### ISSUE THREAD

**Issue by doctorrokter** [TapResearch/react-native-tapresearch#11]
### Env
- `Android` 5.0.1, 5.1.1  (at least)
- `React Native` 0.64.3
- `react-native-tapresearch` 2.4.0
- devices `SCH-I545L`, `SAMSUNG-SM-T337A` (at least)

### Error
The app crash occured when the app tried to initialize TapR SDK:

![image](https://user-images.githubusercontent.com/8337018/145796093-e91ed716-3555-4fea-bccf-f9d7f72d1511.png)
![image](https://user-images.githubusercontent.com/8337018/145796131-c29edb11-6200-40b3-8ba6-96aa988700ad.png)
![image](https://user-images.githubusercontent.com/8337018/145796487-73f16b5d-782d-479f-af72-0c3522a36098.png)

So, the main reason as I assume is:
```NoSuchFieldError: No static field BASE_OS of type Ljava/lang/String; in class Landroid/os/Build$VERSION; or its superclasses (declaration of 'android.os.Build$VERSION' appears in /system/framework/framework.jar)```

@Jjastiny It may relate to a pretty old Android version, maybe SDK utilizes some API which doesn't exist in older Androids. I cannot reproduce on my Android 9 and Android 11 devices.

**Comment by Jjastiny** [comment]
Yes we are using API that's available after Android 6 Marshmallow. Our lint checks missed the api requirement check and ended up missing the flag for this. Although it was a mistake, we are actually now going to move forward to dropping support for Android 5 from our next release

**Comment by doctorrokter** [comment]
> Yes we are using API that's available after Android 6 Marshmallow. Our lint checks missed the api requirement check and ended up missing the flag for this. Although it was a mistake, we are actually now going to move forward to dropping support for Android 5 from our next release

Oh, got it. That makes sense now. Thanks for a quick response!
