### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by drop-ram** [TapResearch/react-native-tapresearch#2]
Hey @icaspi, just doing an integration w/ React Native. Installing the library on a fresh RN app and coming across this error.

```
In file included from /.../testTapResearch/node_modules/react-native-tapresearch/ios/RNTapResearch.m:1:
In file included from /.../testTapResearch/node_modules/react-native-tapresearch/ios/RNTapResearch.h:5:
../../react-native/React/Modules/RCTEventEmitter.h:8:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.

```

~Curious if there is a demo RN app using the latest version of react-native with the integration to take a look.~ [Found it](https://github.com/TapResearch/react-native-integration-demo)

**Comment by drop-ram** [comment]
Just working on this and realized adding a [.podspec](https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec) should resolve the build issues. Will raise a PR for this change.

**Comment by drop-ram** [comment]
Testing on simulator and real device, receiving the following error message w/ this line 

`import RNTapResearch from 'react-native-tapresearch';`

![Simulator Screen Shot - iPhone 11 - 2020-08-12 at 11 35 05](https://user-images.githubusercontent.com/58529645/90042642-f0b8bd00-dc98-11ea-83f6-da30621c21b2.png)

**Comment by Jjastiny** [comment]
Was unable to replicate and has been over 1 year. Closing issue for now
