### ISSUE TITLE
2.3.1 crashes on Android

### ISSUE THREAD

**Issue by doctorrokter** [TapResearch/react-native-tapresearch#8]
The latest `react-native-tapresearch` with version `2.3.1` crashes on Android., works on iOS.

Downgrading to `2.3.0` solves the problem on Android (app doesn't crash), however crashes on iOS.

![image](https://user-images.githubusercontent.com/8337018/140721632-7c28de27-aebf-4fe8-a62c-ec15a64517d0.png)

**Comment by Jjastiny** [comment]
This has been resolved with version 2.4.0
