### ISSUE TITLE
Crash inside TapResearchSDK: NSGenericException Collection <__NSArrayM: 0x280e85a70> was mutated while being enumerated.

### ISSUE THREAD

**Issue by doctorrokter** [TapResearch/react-native-tapresearch#9]
This happens in `react-native-tapresearch` lib with `2.3.1` version on `iOS` (on `Android` that version simply doesn't work as I described here https://github.com/TapResearch/react-native-tapresearch/issues/8).

I see that there are `2.4.0` versions for iOS and Android, but RN SDK still uses older SDKs under the hood!

Please, @icaspi or @Jjastiny, update RN SDK with included bugfixes!

Currently as a workaround, I do `patch-package` and use `2.3.0` Android Native SDK by modifying gradle file (while I still use RN `2.3.1`).

![image](https://user-images.githubusercontent.com/8337018/143862370-ba34ce37-f82d-4a0b-83ea-00938e8818f2.png)

**Comment by Jjastiny** [comment]
Gotcha thanks for the report, it looks like i had notifications disabled. Ill take a look at it. Thanks

**Comment by Jjastiny** [comment]
https://github.com/TapResearch/react-native-integration-demo/pull/13
@doctorrokter
hello, so i was able to use the latest react native version with the latest react native tapresearch sdk and experiencing 0 crashes on both android and iOS. 🎉
